//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloud.VisualStudio.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeCloud.VisualStudio.Shared.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        public static string CloneView_Search {
            get {
                return ResourceManager.GetString("CloneView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个.gitignore.
        /// </summary>
        public static string Common_ChooseAGitIgnore {
            get {
                return ResourceManager.GetString("Common_ChooseAGitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个协议.
        /// </summary>
        public static string Common_ChooseALicense {
            get {
                return ResourceManager.GetString("Common_ChooseALicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 克隆.
        /// </summary>
        public static string Common_Clone {
            get {
                return ResourceManager.GetString("Common_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建仓库.
        /// </summary>
        public static string Common_CreateRepository {
            get {
                return ResourceManager.GetString("Common_CreateRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful collaboration, code review, and code management for open source and private projects..
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git ignore.
        /// </summary>
        public static string Common_GitIgnore {
            get {
                return ResourceManager.GetString("Common_GitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 协议.
        /// </summary>
        public static string Common_License {
            get {
                return ResourceManager.GetString("Common_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeCloud.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Common_New {
            get {
                return ResourceManager.GetString("Common_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路径.
        /// </summary>
        public static string Common_Path {
            get {
                return ResourceManager.GetString("Common_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私有.
        /// </summary>
        public static string Common_Private {
            get {
                return ResourceManager.GetString("Common_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产权.
        /// </summary>
        public static string Common_Property {
            get {
                return ResourceManager.GetString("Common_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSChina.Net.
        /// </summary>
        public static string Common_Provider {
            get {
                return ResourceManager.GetString("Common_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Common_Quit {
            get {
                return ResourceManager.GetString("Common_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要退出吗？.
        /// </summary>
        public static string Confirm_Quit {
            get {
                return ResourceManager.GetString("Confirm_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        public static string CreateView_Description {
            get {
                return ResourceManager.GetString("CreateView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string CreateView_Name {
            get {
                return ResourceManager.GetString("CreateView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接.
        /// </summary>
        public static string Invitation_Connect {
            get {
                return ResourceManager.GetString("Invitation_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Invitation_SignUp {
            get {
                return ResourceManager.GetString("Invitation_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附件.
        /// </summary>
        public static string Items_Attachments {
            get {
                return ResourceManager.GetString("Items_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Items_Issues {
            get {
                return ResourceManager.GetString("Items_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Requests.
        /// </summary>
        public static string Items_PullRequests {
            get {
                return ResourceManager.GetString("Items_PullRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计.
        /// </summary>
        public static string Items_Statistics {
            get {
                return ResourceManager.GetString("Items_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string Items_Wiki {
            get {
                return ResourceManager.GetString("Items_Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接到{0}.
        /// </summary>
        public static string Login_ConnectTo {
            get {
                return ResourceManager.GetString("Login_ConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Publish_Login {
            get {
                return ResourceManager.GetString("Publish_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发布.
        /// </summary>
        public static string Publish_Publish {
            get {
                return ResourceManager.GetString("Publish_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Publish_SignUp {
            get {
                return ResourceManager.GetString("Publish_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发布到{0}.
        /// </summary>
        public static string Publish_Title {
            get {
                return ResourceManager.GetString("Publish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string Repository_Name {
            get {
                return ResourceManager.GetString("Repository_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路径.
        /// </summary>
        public static string Repository_Path {
            get {
                return ResourceManager.GetString("Repository_Path", resourceCulture);
            }
        }
    }
}
