//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloud.VisualStudio.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeCloud.VisualStudio.Shared.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        public static string CloneView_FailedToLoadProjects {
            get {
                return ResourceManager.GetString("CloneView_FailedToLoadProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects.
        /// </summary>
        public static string CloneView_NoProjects {
            get {
                return ResourceManager.GetString("CloneView_NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string CloneView_Search {
            get {
                return ResourceManager.GetString("CloneView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a .gitignore.
        /// </summary>
        public static string Common_ChooseAGitIgnore {
            get {
                return ResourceManager.GetString("Common_ChooseAGitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a license.
        /// </summary>
        public static string Common_ChooseALicense {
            get {
                return ResourceManager.GetString("Common_ChooseALicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string Common_Clone {
            get {
                return ResourceManager.GetString("Common_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Common_CreateRepository {
            get {
                return ResourceManager.GetString("Common_CreateRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of description is 500.
        /// </summary>
        public static string Common_DescriptionMaxTo {
            get {
                return ResourceManager.GetString("Common_DescriptionMaxTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git ignore.
        /// </summary>
        public static string Common_GitIgnore {
            get {
                return ResourceManager.GetString("Common_GitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Common_License {
            get {
                return ResourceManager.GetString("Common_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of name is 64 chars.
        /// </summary>
        public static string Common_NameMaxTo {
            get {
                return ResourceManager.GetString("Common_NameMaxTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Common_New {
            get {
                return ResourceManager.GetString("Common_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Common_Path {
            get {
                return ResourceManager.GetString("Common_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Common_Private {
            get {
                return ResourceManager.GetString("Common_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Common_Property {
            get {
                return ResourceManager.GetString("Common_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Common_Quit {
            get {
                return ResourceManager.GetString("Common_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        public static string Confirm_Quit {
            get {
                return ResourceManager.GetString("Confirm_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is mandatory.
        /// </summary>
        public static string CreateView_NameIsRequired {
            get {
                return ResourceManager.GetString("CreateView_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is mandatory.
        /// </summary>
        public static string CreateView_PathIsRequired {
            get {
                return ResourceManager.GetString("CreateView_PathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a cool project (optional).
        /// </summary>
        public static string CreateView_ThisIsACoollProject {
            get {
                return ResourceManager.GetString("CreateView_ThisIsACoollProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful collaboration, code review, and code management for open source and private projects..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Invitation_Connect {
            get {
                return ResourceManager.GetString("Invitation_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Invitation_SignUp {
            get {
                return ResourceManager.GetString("Invitation_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Items_Attachments {
            get {
                return ResourceManager.GetString("Items_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Items_Issues {
            get {
                return ResourceManager.GetString("Items_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Requests.
        /// </summary>
        public static string Items_PullRequests {
            get {
                return ResourceManager.GetString("Items_PullRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Items_Statistics {
            get {
                return ResourceManager.GetString("Items_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string Items_Wiki {
            get {
                return ResourceManager.GetString("Items_Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to {0}.
        /// </summary>
        public static string Login_ConnectTo {
            get {
                return ResourceManager.GetString("Login_ConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string Login_EmailIsInvalid {
            get {
                return ResourceManager.GetString("Login_EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is mandatory.
        /// </summary>
        public static string Login_EmailIsRequired {
            get {
                return ResourceManager.GetString("Login_EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login.
        /// </summary>
        public static string Login_FailedToLogin {
            get {
                return ResourceManager.GetString("Login_FailedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        public static string Login_ForgetPassword {
            get {
                return ResourceManager.GetString("Login_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is mandatory.
        /// </summary>
        public static string Login_PasswordIsRequired {
            get {
                return ResourceManager.GetString("Login_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should at least be 6 chars.
        /// </summary>
        public static string Login_PasswordMinTo {
            get {
                return ResourceManager.GetString("Login_PasswordMinTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resent email to active account.
        /// </summary>
        public static string Login_ReSendEmail {
            get {
                return ResourceManager.GetString("Login_ReSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeCloud.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSChina.Net.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Publish_Login {
            get {
                return ResourceManager.GetString("Publish_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Publish_Or {
            get {
                return ResourceManager.GetString("Publish_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish_Publish {
            get {
                return ResourceManager.GetString("Publish_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Publish_SignUp {
            get {
                return ResourceManager.GetString("Publish_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Publish_Start {
            get {
                return ResourceManager.GetString("Publish_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting.
        /// </summary>
        public static string Publish_Submiting {
            get {
                return ResourceManager.GetString("Publish_Submiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to {0}.
        /// </summary>
        public static string Publish_Title {
            get {
                return ResourceManager.GetString("Publish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Repository_Name {
            get {
                return ResourceManager.GetString("Repository_Name", resourceCulture);
            }
        }
    }
}
