//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitLab.VisualStudio.Shared {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitLab.VisualStudio.Shared.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load 的本地化字符串。
        /// </summary>
        public static string CloneView_FailedToLoadProjects {
            get {
                return ResourceManager.GetString("CloneView_FailedToLoadProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No projects 的本地化字符串。
        /// </summary>
        public static string CloneView_NoProjects {
            get {
                return ResourceManager.GetString("CloneView_NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string CloneView_Search {
            get {
                return ResourceManager.GetString("CloneView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a .gitignore 的本地化字符串。
        /// </summary>
        public static string Common_ChooseAGitIgnore {
            get {
                return ResourceManager.GetString("Common_ChooseAGitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a license 的本地化字符串。
        /// </summary>
        public static string Common_ChooseALicense {
            get {
                return ResourceManager.GetString("Common_ChooseALicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone 的本地化字符串。
        /// </summary>
        public static string Common_Clone {
            get {
                return ResourceManager.GetString("Common_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Common_CreateRepository {
            get {
                return ResourceManager.GetString("Common_CreateRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum length of description is 500 的本地化字符串。
        /// </summary>
        public static string Common_DescriptionMaxTo {
            get {
                return ResourceManager.GetString("Common_DescriptionMaxTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Git ignore 的本地化字符串。
        /// </summary>
        public static string Common_GitIgnore {
            get {
                return ResourceManager.GetString("Common_GitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License 的本地化字符串。
        /// </summary>
        public static string Common_License {
            get {
                return ResourceManager.GetString("Common_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum length of name is 64 chars 的本地化字符串。
        /// </summary>
        public static string Common_NameMaxTo {
            get {
                return ResourceManager.GetString("Common_NameMaxTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string Common_New {
            get {
                return ResourceManager.GetString("Common_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Common_Path {
            get {
                return ResourceManager.GetString("Common_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private 的本地化字符串。
        /// </summary>
        public static string Common_Private {
            get {
                return ResourceManager.GetString("Common_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        public static string Common_Property {
            get {
                return ResourceManager.GetString("Common_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string Common_Quit {
            get {
                return ResourceManager.GetString("Common_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to quit? 的本地化字符串。
        /// </summary>
        public static string Confirm_Quit {
            get {
                return ResourceManager.GetString("Confirm_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name is mandatory 的本地化字符串。
        /// </summary>
        public static string CreateView_NameIsRequired {
            get {
                return ResourceManager.GetString("CreateView_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path is mandatory 的本地化字符串。
        /// </summary>
        public static string CreateView_PathIsRequired {
            get {
                return ResourceManager.GetString("CreateView_PathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a cool project (optional) 的本地化字符串。
        /// </summary>
        public static string CreateView_ThisIsACoollProject {
            get {
                return ResourceManager.GetString("CreateView_ThisIsACoollProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The project {0} already exists! 的本地化字符串。
        /// </summary>
        public static string CreateViewModel_OnSave_TheProject0AlreadyExists {
            get {
                return ResourceManager.GetString("CreateViewModel_OnSave_TheProject0AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitLab  unlimited free repositories and collaborators. Sign Up. Free public &amp; private repositories and unlimited collaborators. 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        public static string Invitation_Connect {
            get {
                return ResourceManager.GetString("Invitation_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign up 的本地化字符串。
        /// </summary>
        public static string Invitation_SignUp {
            get {
                return ResourceManager.GetString("Invitation_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Builds 的本地化字符串。
        /// </summary>
        public static string Items_builds {
            get {
                return ResourceManager.GetString("Items_builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphs 的本地化字符串。
        /// </summary>
        public static string Items_Graph {
            get {
                return ResourceManager.GetString("Items_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issues 的本地化字符串。
        /// </summary>
        public static string Items_Issues {
            get {
                return ResourceManager.GetString("Items_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Requests 的本地化字符串。
        /// </summary>
        public static string Items_MergeRequests {
            get {
                return ResourceManager.GetString("Items_MergeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pipelines 的本地化字符串。
        /// </summary>
        public static string Items_Pipeline {
            get {
                return ResourceManager.GetString("Items_Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippets 的本地化字符串。
        /// </summary>
        public static string Items_Snippets {
            get {
                return ResourceManager.GetString("Items_Snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wiki 的本地化字符串。
        /// </summary>
        public static string Items_Wiki {
            get {
                return ResourceManager.GetString("Items_Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect to {0} 的本地化字符串。
        /// </summary>
        public static string Login_ConnectTo {
            get {
                return ResourceManager.GetString("Login_ConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name or Email  的本地化字符串。
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid email 的本地化字符串。
        /// </summary>
        public static string Login_EmailIsInvalid {
            get {
                return ResourceManager.GetString("Login_EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email is mandatory 的本地化字符串。
        /// </summary>
        public static string Login_EmailIsRequired {
            get {
                return ResourceManager.GetString("Login_EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to login 的本地化字符串。
        /// </summary>
        public static string Login_FailedToLogin {
            get {
                return ResourceManager.GetString("Login_FailedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forget password? 的本地化字符串。
        /// </summary>
        public static string Login_ForgetPassword {
            get {
                return ResourceManager.GetString("Login_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitLab(https://gitlab.com) 的本地化字符串。
        /// </summary>
        public static string Login_Host {
            get {
                return ResourceManager.GetString("Login_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host is invalid 的本地化字符串。
        /// </summary>
        public static string Login_HostIsInvalid {
            get {
                return ResourceManager.GetString("Login_HostIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password is mandatory 的本地化字符串。
        /// </summary>
        public static string Login_PasswordIsRequired {
            get {
                return ResourceManager.GetString("Login_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password should at least be 6 chars 的本地化字符串。
        /// </summary>
        public static string Login_PasswordMinTo {
            get {
                return ResourceManager.GetString("Login_PasswordMinTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resent email to active account 的本地化字符串。
        /// </summary>
        public static string Login_ReSendEmail {
            get {
                return ResourceManager.GetString("Login_ReSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign up 的本地化字符串。
        /// </summary>
        public static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitLab 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitLab 的本地化字符串。
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Publish_Login {
            get {
                return ResourceManager.GetString("Publish_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        public static string Publish_Or {
            get {
                return ResourceManager.GetString("Publish_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish 的本地化字符串。
        /// </summary>
        public static string Publish_Publish {
            get {
                return ResourceManager.GetString("Publish_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign up 的本地化字符串。
        /// </summary>
        public static string Publish_SignUp {
            get {
                return ResourceManager.GetString("Publish_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Publish_Start {
            get {
                return ResourceManager.GetString("Publish_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submitting 的本地化字符串。
        /// </summary>
        public static string Publish_Submiting {
            get {
                return ResourceManager.GetString("Publish_Submiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish to {0} 的本地化字符串。
        /// </summary>
        public static string Publish_Title {
            get {
                return ResourceManager.GetString("Publish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Repository_Name {
            get {
                return ResourceManager.GetString("Repository_Name", resourceCulture);
            }
        }
    }
}
