// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitLab.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenOnGitLabPackageString = "4549d811-2209-4fde-9fe6-ef50ebe00ca0";
        public const string guidOpenOnGitLabPackageCmdSetString = "6cd6c755-f5a3-4944-a799-44b346edd2ea";
        public const string guidImagesString = "357e513c-c4df-4cd6-8db9-f4104f708c5c";
        public static Guid guidOpenOnGitLabPackage = new Guid(guidOpenOnGitLabPackageString);
        public static Guid guidOpenOnGitLabPackageCmdSet = new Guid(guidOpenOnGitLabPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CommandId_OpenMaster = 0x0100;
        public const int CommandId_OpenBranch = 0x0200;
        public const int CommandId_OpenRevision = 0x0300;
        public const int CommandId_OpenRevisionFull = 0x0400;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
