// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitLab.VisualStudio
{
    static class Vsix
    {
        public const string Id = "54803a44-49e0-4935-bba4-7d7d91682273";
        public const string Name = "GitLab Extension for Visual Studio";
        public const string Description = @"A Visual Studio Extension that brings the GitLab Flow into Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0.0.129";
        public const string Author = "MysticBoy";
        public const string Tags = "GitLab;git;open source;source control;branch;Pipelines;Registry;Graphs;IssuesMerge Requests;Wiki";
    }
}
