// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.201
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitLab.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGitLabPackagePkgString = "54803a44-49e0-4935-bba4-7d7d91682273";
        public const string guidOpenOnGitLabCmdSetString = "72b54f2e-fe93-4950-88bf-c536d1cfd91f";
        public const string guidIssuesToolWindowPackageCmdSetString = "78e9c435-500f-4e4d-8e31-dc16d9f26032";
        public const string HtmlEditorWindowLibraString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public const string CssEditorWindows2String = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public const string JsonEditorWindowsString = "f718ca06-cf4f-4a0c-9106-e79e9ee5e7cd";
        public const string HtmlEditorWindowsString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public const string CssEditorWindowsString = "a764e896-518d-11d2-9a89-00c04f79efc3";
        public const string XamlEditorWindowsString = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public static Guid guidGitLabPackagePkg = new Guid(guidGitLabPackagePkgString);
        public static Guid guidOpenOnGitLabCmdSet = new Guid(guidOpenOnGitLabCmdSetString);
        public static Guid guidIssuesToolWindowPackageCmdSet = new Guid(guidIssuesToolWindowPackageCmdSetString);
        public static Guid HtmlEditorWindowLibra = new Guid(HtmlEditorWindowLibraString);
        public static Guid CssEditorWindows2 = new Guid(CssEditorWindows2String);
        public static Guid JsonEditorWindows = new Guid(JsonEditorWindowsString);
        public static Guid HtmlEditorWindows = new Guid(HtmlEditorWindowsString);
        public static Guid CssEditorWindows = new Guid(CssEditorWindowsString);
        public static Guid XamlEditorWindows = new Guid(XamlEditorWindowsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContextMenuGroup = 0x1020;
        public const int SubMenuGroup = 0x1030;
        public const int SubMenu = 0x1040;
        public const int OpenMaster = 0x0100;
        public const int OpenBranch = 0x0200;
        public const int OpenRevision = 0x0300;
        public const int OpenRevisionFull = 0x0400;
        public const int OpenBlame = 0x0500;
        public const int OpenCommits = 0x0600;
        public const int OpenCreateSnippet = 0x0700;
        public const int IssuesToolWindowCommandId = 0x0800;
        public const int IDMX_HTML_SOURCE = 0x0001;
        public const int IDMX_CSS_SOURCE = 0x0002;
        public const int IDMX_JSON_SOURCE = 0x0003;
        public const int IDMX_HTM_SOURCE_BASIC = 0x0032;
        public const int IDMX_HTM_SOURCE_HTML = 0x0033;
        public const int IDMX_HTM_SOURCE_SCRIPT = 0x0034;
        public const int IDMX_HTM_SOURCE_ASPX = 0x0035;
        public const int IDMX_HTM_SOURCE_ASAX = 0x003B;
        public const int IDMX_HTM_SOURCE_ASPX_CODE = 0x0036;
        public const int IDMX_HTM_SOURCE_ASAX_CODE = 0x003C;
        public const int IDMX_HTM_SOURCE_ASPX_CODE_VB = 0x0037;
        public const int IDMX_HTM_SOURCE_ASAX_CODE_VB = 0x003D;
        public const int IDMX_HTM_SOURCE_ASMX_CODE = 0x0038;
        public const int IDMX_HTM_SOURCE_ASMX_CODE_VB = 0x0039;
        public const int IDMX_HTM_SOURCE_CSS = 0x0102;
        public const int IDMX_XAML_SOURCE_BASIC = 0x0103;
    }
}
